plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.4'
    modules = ['javafx.controls']
}

application {
    // Launcher (e nao MainApp) para nao esbarrar no
    // "JavaFX runtime components are missing" ao rodar do classpath.
    mainClass = 'rps.ui.Launcher'
}
